site_name: PySimpleGUI
# mkdocs.yml:

nav:
    ## add your custom pages hierarchy here

theme:
  name: null
  custom_dir: 'rtd_dropdown'
  include_search_page: true
  search_index_only: false
  static_templates:
  - 404.html

plugins: ['search']

# add theme version number here
extra:
    version: 0.3.x
