site_name: PySimpleGUI
# mkdocs.yml:
repo_url: https://github.com/PySimpleGUI/PySimpleGUI
nav:
    ## add your custom pages hierarchy here

theme:
  name: null
  custom_dir: 'mkdocs_ivory'
  include_search_page: true
  search_index_only: false
  static_templates:
  - 404.html

plugins: ['search']

# add theme version number here
extra:
    version: 0.3.x
